Delete draft releases when PR is closed

diff --git a/.github/workflows/create-draft-release.yaml b/.github/workflows/create-draft-release.yaml
--- a/.github/workflows/create-draft-release.yaml
+++ b/.github/workflows/create-draft-release.yaml
@@ -11,8 +11,6 @@ jobs:
       with:
         fetch-depth: '0'
         fetch-tags: 'true'
-    - name: Check gh cli
-      run: which gh
     - name: Set up git identity
       run: |
         git config --local user.email "dev@giantswarm.io"
@@ -54,5 +52,30 @@ jobs:
           else
             echo "Found existing draft release $draft_tag_name, will update it."
             gh release upload --repo giantswarm/releases --clobber "$draft_tag_name" "$aws_release_dir/release.yaml" 
+          fi
+        done
+
+
+  delete_draft_release:
+    if: github.event_name == 'pull_request' && github.event.action == 'closed'
+    runs-on: ubuntu-latest
+    steps:
+    - name: Checkout code
+      uses: actions/checkout@v2
+      with:
+        fetch-depth: '0'
+    - name: Delete draft releases and tags
+      env:
+        GITHUB_TOKEN: "${{ secrets.TAYLORBOT_GITHUB_ACTION }}"
+      run: |
+        for aws_release_dir in capa/*; do
+          aws_release_version="$(basename $aws_release_dir)"
+          draft_tag_name="draft/aws/$aws_release_version"
+          draft_release=$(gh release --repo giantswarm/releases view "$draft_tag_name" --json "id,name,tagName,assets,isDraft,isPrerelease,url" 2>&1 || true)
+          if [ "$draft_release" = "release not found" ]; then
+            echo "Draft release not found for tag $draft_tag_name"
+          else
+            echo "Found existing draft release $draft_tag_name, will delete it."
+            gh release delete --repo giantswarm/releases "$draft_tag_name" --yes --cleanup-tag
           fi
         done
